# Generated by Django 5.0.2 on 2024-03-12 12:57

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carousel_image", models.ImageField(upload_to="carousel_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Category"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=300, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the department. Example: 'Mathematics', 'Humanities'  ",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: i.e 'Mr', 'Mrs', 'Miss'",
                        max_length=5,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=10)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("PRINCIPAL", "Principal"),
                            ("DEPUTY", "Deputy Principal"),
                            ("ADMINISTRATOR", "Administrator"),
                            ("DIRECTOR", "Board Director"),
                            ("TEACHER", "Teacher"),
                            ("NTS", "None Teaching Staff"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional. The department the staff member belongs to.",
                        max_length=100,
                    ),
                ),
                (
                    "picture",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        default="defaults/default-no-user-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[600, 600],
                        upload_to="staff/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=500, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="Date Modified"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Date Deleted",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=500, unique=True
                    ),
                ),
                (
                    "entry",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "---------"),
                            ("ADMINISTRATION", "Administration"),
                            ("ADMISSION", "Admissions"),
                            ("ACADEMIC", "Academic"),
                            ("CURRICULAR", "Co-Curricular"),
                            ("HISTORY", "School History"),
                            ("PRINCIPLES", "Principles"),
                            ("MESSAGE", "Principals Message"),
                            ("EXTRA", "Extra"),
                        ],
                        default=(None, "---------"),
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=150)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "cover_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="defaults/default-no-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="entries/",
                    ),
                ),
                (
                    "parent_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="home.entry",
                        verbose_name="Parent Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Info Entry",
                "verbose_name_plural": "School Info Entries",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery_image", models.ImageField(upload_to="gallery/")),
                (
                    "thumbnail",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        editable=False,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[500, 500],
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=250)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "news_image",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        default="defaults/default-no-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="news/",
                    ),
                ),
                ("post_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modification_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=500, unique=True
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=models.SET(home.models.get_sentinel_user),
                        to="home.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-post_date"],
            },
        ),
    ]
