# Generated by Django 4.2.2 on 2023-08-10 17:10

import django_ckeditor_5.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import home.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Category"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the department. Example: 'Mathematics', 'Humanities'  ",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_info",
                    models.TextField(
                        blank=True,
                        default="Welcome to Moi Kadzonzo Girls High School website. It is designed for parents, students, Alumni, staff, sponsors, friends of the school and prospective parents who may know little about us.",
                        max_length=300,
                    ),
                ),
                (
                    "administration_info",
                    models.TextField(
                        blank=True,
                        default="Meet our team of experienced professionals who manage and lead our organization. Our administration is dedicated to providing the best possible service to our clients and stakeholders.",
                        max_length=300,
                    ),
                ),
                (
                    "administration_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "administration_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: Short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                (
                    "academics_info",
                    models.TextField(
                        blank=True,
                        default="Our educational programs are designed to prepare students for success in their chosen careers. We offer a wide range of courses and programs, from technical training to liberal arts and sciences.",
                        max_length=300,
                    ),
                ),
                (
                    "academics_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "academics_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True, default="", max_length=255
                    ),
                ),
                (
                    "staff_info",
                    models.TextField(
                        blank=True,
                        default="Our staff is made up of dedicated and talented individuals who are committed to providing excellent service to our clients and customers. They bring a wealth of experience and expertise to their roles, ensuring that we deliver the highest quality work.",
                        max_length=300,
                    ),
                ),
                (
                    "staff_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "staff_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: Short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                (
                    "curricular_info",
                    models.TextField(
                        blank=True,
                        default="Our curricular activities are designed to provide students with opportunities to explore their interests, develop new skills, and build relationships with peers. We offer a wide range of activities, from sports teams and clubs to music and theater programs.",
                        max_length=300,
                    ),
                ),
                (
                    "curricular_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "curricular_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: Short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                (
                    "library_info",
                    models.TextField(
                        blank=True,
                        default="Our library is a vital resource for students and researchers, providing access to a wide range of books, journals, and digital resources. Our knowledgeable staff is available to assist with research and information inquiries.",
                        max_length=300,
                    ),
                ),
                (
                    "library_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "library_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: Short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                (
                    "alumni_info",
                    models.TextField(
                        blank=True,
                        default="Our alumni are an important part of our community, and we are proud of their accomplishments and contributions. We maintain strong relationships with our alumni, providing opportunities for networking, professional development, and social events.",
                        max_length=300,
                    ),
                ),
                (
                    "alumni_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="homeFeatures/",
                    ),
                ),
                (
                    "alumni_image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: Short description of what the image entails.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "cover_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="about/",
                    ),
                ),
                (
                    "image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titles and other words associated with a person's name. Example: 'Mr', 'Mrs', 'Miss'",
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "picture",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        default="default value",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[600, 600],
                        upload_to="staff/",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=10)),
                ("message", models.TextField(blank=True, max_length=1000)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Optional. The role of the staff member. Example: 'Principal', 'Deputy Principal', 'HOD'",
                        max_length=30,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Optional. The department the staff member belongs to.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                ("academics_info", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="Administration",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                ("admin_info", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                ("admission_info", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="Curricular",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                ("curricular_info", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="SchoolHistory",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="SchoolValue",
            fields=[
                (
                    "schoolinfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.schoolinfo",
                    ),
                ),
                (
                    "motto",
                    models.TextField(
                        default="Bright Shining Star of Academic Excellence in the Nation.",
                        max_length=500,
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        default="Instilling Self-Esteem And Empowering The Girl Child For The Competitive Market In Life.",
                        max_length=500,
                    ),
                ),
                (
                    "vision",
                    models.TextField(
                        default="To Be A Bright Shining Star of Academic Excellence In The Nation.",
                        max_length=500,
                    ),
                ),
            ],
            bases=("home.schoolinfo",),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=250)),
                ("news", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "news_image",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        default="default-image.jpg",
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1920, 1300],
                        upload_to="news/",
                    ),
                ),
                (
                    "image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                ("post_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modification_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=models.SET(home.models.get_sentinel_user),
                        to="home.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-post_date"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery_image", models.ImageField(upload_to="gallery/")),
                (
                    "image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                (
                    "thumbnail",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        editable=False,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[500, 500],
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.category",
                    ),
                ),
            ],
        ),
    ]
