# Generated by Django 4.2.2 on 2023-08-15 14:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carousel_image", models.ImageField(upload_to="carousel_images/")),
                (
                    "image_alt_text",
                    home.models.ImageAltTextField(
                        blank=True,
                        help_text="Optional: short description of what the image entails.",
                        max_length=255,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
