# Generated by Django 4.2.2 on 2023-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolinfo",
            old_name="image",
            new_name="cover_image",
        ),
        migrations.RemoveField(
            model_name="academic",
            name="subject",
        ),
    ]
