# Generated by Django 5.0.2 on 2024-03-19 17:45

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="carousel_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=90,
                scale=None,
                size=[1920, 1080],
                upload_to="carousel_images/",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="cover_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="defaults/default-no-image.jpg",
                force_format=None,
                keep_meta=True,
                quality=90,
                scale=None,
                size=[1920, 1300],
                upload_to="entries/",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="defaults/default-no-image.jpg",
                force_format=None,
                keep_meta=True,
                quality=90,
                scale=None,
                size=[1920, 1300],
                upload_to="news/",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="defaults/default-no-user-image.jpg",
                force_format=None,
                keep_meta=True,
                quality=90,
                scale=None,
                size=[600, 600],
                upload_to="staff/",
            ),
        ),
    ]
