# Generated by Django 5.0.2 on 2024-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="defaults/default-no-image.jpg",
                upload_to="entries/",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="thumbnail",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="gallery/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_image",
            field=models.ImageField(
                default="defaults/default-no-image.jpg", upload_to="news/"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="defaults/default-no-user-image.jpg",
                upload_to="staff/",
            ),
        ),
    ]
