# Generated by Django 4.2.2 on 2023-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_carouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolinfo",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
