# Generated by Django 5.0.2 on 2024-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_entry_cover_image_alter_gallery_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselimage",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="news",
            name="image_alt_text",
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
