# Generated by Django 5.0.2 on 2024-04-02 17:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("home", "0004_joblisting"),
        ("home", "0005_alter_joblisting_options_and_more"),
        ("home", "0006_rename_name_joblisting_title_and_more"),
    ]

    dependencies = [
        ("home", "0003_alter_entry_options_alter_staff_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Job Title")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ongoing"), (0, "Closed")], default=1
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(verbose_name="Application Deadline"),
                ),
                (
                    "date_listed",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Listed"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=500, unique=True
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Job Description",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        default="", max_length=50, verbose_name="Experience Level"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Employment Type",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_listed"],
            },
        ),
    ]
