# Generated by Django 5.0.2 on 2024-02-28 15:42

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_administration_schoolinfo_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeFeature",
        ),
        migrations.AddField(
            model_name="entry",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="entry",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "---------"),
                    ("ADMINISTRATION", "Administration"),
                    ("ADMISSION", "Admissions"),
                    ("ACADEMIC", "Academic"),
                    ("CURRICULAR", "Co-Curricular"),
                    ("HISTORY", "School History"),
                    ("PRINCIPLES", "Principles"),
                    ("EXTRA", "Extra"),
                ],
                default=(None, "---------"),
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="",
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1920, 1300],
                upload_to="news/",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="",
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[600, 600],
                upload_to="staff/",
            ),
        ),
    ]
