# Generated by Django 5.0.2 on 2024-02-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_delete_homefeature_entry_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=300, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=500, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=500, unique=True
            ),
        ),
    ]
