# Generated by Django 5.0.2 on 2024-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_category_slug_alter_entry_slug_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="entry",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "---------"),
                    ("ADMINISTRATION", "Administration"),
                    ("ADMISSION", "Admissions"),
                    ("ACADEMIC", "Academic"),
                    ("CURRICULAR", "Co-Curricular"),
                    ("HISTORY", "School History"),
                    ("PRINCIPLES", "Principles"),
                    ("MESSAGE", "Principals Message"),
                    ("EXTRA", "Extra"),
                ],
                default=(None, "---------"),
                max_length=15,
            ),
        ),
    ]
