# Generated by Django 5.0.2 on 2024-03-06 09:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_entry_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="news",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="message",
        ),
        migrations.AddField(
            model_name="news",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="full_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional. The department the staff member belongs to.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("PRINCIPAL", "Principal"),
                    ("DEPUTY", "Deputy Principal"),
                    ("BOM", "Board of Management"),
                    ("TEACHER", "Teacher"),
                    ("NTS", "None Teaching Staff"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: i.e 'Mr', 'Mrs', 'Miss'",
                max_length=5,
            ),
        ),
    ]
