# Generated by Django 5.0.2 on 2024-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("PRINCIPAL", "Principal"),
                    ("DEPUTY", "Deputy Principal"),
                    ("ADMINISTRATOR", "Administrator"),
                    ("DIRECTOR", "Board Director"),
                    ("TEACHER", "Teacher"),
                    ("NTS", "None Teaching Staff"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
