# Generated by Django 5.0.2 on 2024-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_staff_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="publisher",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
